### ISSUE TITLE
Checklist 1.0

### ISSUE THREAD

**Issue by Fudoshiki** [Youimmi/phoenix_asset_pipeline#8]
## exec

- [ ] [esbuild](/phoenixframework/esbuild)
- [ ] [coffee](/jashkenas/coffeescript/)
- [ ] [dart-sass](/sass/dart-sass)
- [ ] [brotli](/google/brotli)

## options

- [ ] yarn [pnp](https://yarnpkg.com/features/pnp) and [zero-install](https://yarnpkg.com/features/zero-installs) support
- [ ] [closure-compiler](/google/closure-compiler)

## refs

- https://github.com/google/closure-stylesheets
- https://github.com/mnussbaumer/cssex
- https://elixirforum.com/t/dartsass-an-installer-for-sass/41371
- https://medium.com/dartlang/experimenting-with-dart-and-wasm-ef7f1c065577
- https://github.com/CargoSense/dart_sass
